config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'db_schemas#index'
  resources :db_schemas, except: [:edit]
  get "/db_schemas/:db_schema_id/sharings/:token", to: "sharings#create", as: :db_schema_sharings
  post "/db_schemas/:id", to: "db_schemas#update"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/db_schema.rb
class DbSchema < ApplicationRecord
  belongs_to :user
  has_many :sharings
  before_create :set_token

  def set_token
    self.token = SecureRandom.hex(25)
  end
end

app/models/sharing.rb
class Sharing < ApplicationRecord
  belongs_to :user
  belongs_to :db_schema
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :db_schemas
  has_many :sharings
  has_many :shared_db_schemas, through: :sharings, source: :db_schemas
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  include Pundit

  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  # after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/db_schemas_controller.rb
class DbSchemasController < ApplicationController
  before_action :set_db_schema, only: [:show, :edit, :update, :destroy]
  after_action :authorize_db_schema, except: [:index]
  layout 'sqldesigner', only: :show

  def show;end

  def index
    @my_db_schemas     = current_user.db_schemas
    @db_schema_sharing = current_user.sharings.map(&:db_schema)
  end

  def new
    @db_schema = DbSchema.new
  end

  def create
    @db_schema =DbSchema.new(db_schema_params)
    @db_schema.user = current_user
    if @db_schema.save
      redirect_to db_schema_path(@db_schema)
    else
      render :new
    end
  end

  def update
    # binding.pry
    # puts params
    @db_schema.content = request.raw_post
    if @db_schema.save
      redirect_to db_schema_path(@db_schema)
    else
      render :edit
    end
  end

  def destroy
    @db_schema.destroy
    redirect_ot
  end

  private

  def db_schema_params
    params.require(:db_schema).permit(:content, :name)
  end

  def set_db_schema
    @db_schema = DbSchema.find(params[:id])
  end

  def authorize_db_schema
    authorize @db_schema
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/controllers/sharings_controller.rb
class SharingsController < ApplicationController
  before_action :set_db_schema, only: [:create]

  def create
    @sharing = Sharing.new(user: current_user, db_schema: @db_schema)
    authorize @sharing
    if params[:token] == @db_schema.token
      @sharing.save
      redirect_to db_schema_path(@db_schema)
    else
      flash[:alert] = "This action is not available"
      redirect_to root_path
    end
  end

  private

  def set_db_schema
    @db_schema = DbSchema.find(params[:db_schema_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/db_schemas/_form.html.erb
<%= simple_form_for @db_schema do |f| %>
  <%= f.input :name %>
  <%= f.input :content %>
  <%= f.submit "Create a DB Schema", class: "btn btn-primary" %>
<% end %>

app/views/db_schemas/edit.html.erb
<%= render "db_schemas/form" %>

app/views/db_schemas/index.html.erb
<div class="container">
  <div class="row mt-5">
    <div class="col">
      <div class="d-flex justify-content-between">
        <h2>My <%= @my_db_schemas.size %> DB schemas</h2>
        <%= link_to "Add a schema", new_db_schema_path, class: "btn btn-primary" %>
      </div>
      <ul>
        <% @my_db_schemas.each do |db_schema| %>
          <li>
            <%= link_to db_schema.name, db_schema_path(db_schema) %>
            <br>
            <p><%= db_schema_sharings_url(db_schema, token: db_schema.token) %></p>
          </li>
        <% end %>
      </ul>
    </div>
  </div>

    <div class="row mt-5">
      <div class="col">
        <div class="d-flex justify-content-between">
          <h2>Contributing on <%= @db_schema_sharing.size %> DB schemas</h2>
        </div>
        <ul>
          <% @db_schema_sharing.each do |db_schema| %>
            <li>
              <%= link_to db_schema.name, db_schema_path(db_schema) %>
              <br>
              <p><%= db_schema_sharings_url(db_schema, token: db_schema.token) %></p>
              </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/db_schemas/new.html.erb
<%= render "db_schemas/form" %>

app/views/db_schemas/show.html.erb
<div class="row">
  <div class="col">
    <%= link_to "Back to Db Schema List", db_schemas_path %>
  </div>
</div>
<div id="wwwsqldesigner">
  <div id="area"></div>

  <div id="controls">
    <div id="bar">
      <div id="toggle"></div>
      <input type="button" id="saveload" />

      <hr/>

      <input type="button" id="addtable" />
      <input type="button" id="edittable" />
      <input type="button" id="tablekeys" style="display: none" />
      <input type="button" id="removetable" />
      <input type="button" id="aligntables" style="display: none" />
      <input type="button" id="cleartables" />

      <hr/>

      <input type="button" id="addrow" />
      <input type="button" id="editrow" />
      <input type="button" id="uprow" class="small" /><input type="button" id="downrow" class="small"/>
      <input type="button" id="foreigncreate" />
      <input type="button" id="foreignconnect" />
      <input type="button" id="foreigndisconnect" />
      <input type="button" id="removerow" />

      <input type="button" id="options" style="display: none"/>
      <a href="https://github.com/ondras/wwwsqldesigner/wiki" target='_blank'><input type="button" id="docs" value=""  style="display: none"/></a>
    </div>

    <div id="rubberband"></div>

    <div id="minimap"></div>

    <div id="background"></div>

    <div id="window">
      <div id="windowtitle">
        <%= image_tag "wwwsqldesigner/images/throbber.gif", id: 'throbber' %>
        <!-- <img id="throbber" src="images/throbber.gif" alt="" title=""/> -->
      </div>
      <div id="windowcontent"></div>
      <input type="button" id="windowok" />
      <input type="button" id="windowcancel" />
    </div>
  </div> <!-- #controls -->

  <div id="opts">
    <table>
      <tbody>
        <tr>
          <td>
            * <label id="language" for="optionlocale"></label>
          </td>
          <td>
            <select id="optionlocale"><option></option></select>
          </td>
        </tr>
        <tr>
          <td>
            * <label id="db" for="optiondb"></label>
          </td>
          <td>
            <select id="optiondb"><option></option></select>
          </td>
        </tr>
        <tr>
          <td>
            <label id="snap" for="optionsnap"></label>
          </td>
          <td>
            <input type="text" size="4" id="optionsnap" />
            <span class="small" id="optionsnapnotice"></span>
          </td>
        </tr>
        <tr>
          <td>
            <label id="pattern" for="optionpattern"></label>
          </td>
          <td>
            <input type="text" size="6" id="optionpattern" />
            <span class="small" id="optionpatternnotice"></span>
          </td>
        </tr>
        <tr>
          <td>
            <label id="hide" for="optionhide"></label>
          </td>
          <td>
            <input type="checkbox" id="optionhide" />
          </td>
        </tr>
        <tr>
          <td>
            * <label id="vector" for="optionvector"></label>
          </td>
          <td>
            <input type="checkbox" id="optionvector" />
          </td>
        </tr>
        <tr>
          <td>
            * <label id="showsize" for="optionshowsize"></label>
          </td>
          <td>
            <input type="checkbox" id="optionshowsize" />
          </td>
        </tr>
        <tr>
          <td>
            * <label id="showtype" for="optionshowtype"></label>
          </td>
          <td>
            <input type="checkbox" id="optionshowtype" />
          </td>
        </tr>
      </tbody>
    </table>

    <hr />

    * <span class="small" id="optionsnotice"></span>
  </div>

  <div id="io">
    <table>
      <tbody>
        <tr>
          <td style="width:60%">
            <fieldset>
              <legend id="client"></legend>
              <div id="singlerow">
              <input type="button" id="clientsave" />
              <input type="button" id="clientload" />
              </div>
              <div id="singlerow"  style="display: none">
              <input type="button" id="clientlocalsave" style="display: none" />
              <input type="button" id="clientlocalload" style="display: none" />
              <input type="button" id="clientlocallist" style="display: none" />
              </div>
              <div id="singlerow" style="display: none">
                <input type="button" id="dropboxsave" /><!-- may get hidden by dropBoxInit() -->
                <input type="button" id="dropboxload" /><!-- may get hidden by dropBoxInit() -->
                <input type="button" id="dropboxlist" /><!-- may get hidden by dropBoxInit() -->
              </div>
              <input type="button" id="clientsql" style="display: none" />
            </fieldset>
          </td>
          <td style="width:40%">
            <fieldset>
              <legend id="server"></legend>
              <label style="display: none" for="backend" id="backendlabel"></label>
              <select id="backend" style="display: none"><option></option></select>
              <input type="button" id="serversave"  style="display: none" />
              <input type="button" id="quicksave" />
              <input type="button" id="serverload"  style="display: none"/>
              <input type="button" id="serverlist" style="display: none" />
              <input type="button" id="serverimport" style="display: none" />
            </fieldset>
          </td>
        </tr>
        <tr>
          <td colspan="2">
            <fieldset>
              <legend id="output"></legend>
              <textarea id="textarea" rows="1" cols="1"></textarea><!--modified by javascript later-->
            </fieldset>
          </td>
        </tr>
      </tbody>
    </table>
  </div>

  <div id="keys">
    <fieldset>
      <legend id="keyslistlabel"></legend>
      <select id="keyslist"><option></option></select>
      <input type="button" id="keyadd" />
      <input type="button" id="keyremove" />
    </fieldset>
    <fieldset>
      <legend id="keyedit"></legend>
      <table>
        <tbody>
          <tr>
            <td>
              <label for="keytype" id="keytypelabel"></label>
              <select id="keytype"><option></option></select>
            </td>
            <td></td>
            <td>
              <label for="keyname" id="keynamelabel"></label>
              <input type="text" id="keyname" size="10" />
            </td>
          </tr>
          <tr>
            <td colspan="3"><hr/></td>
          </tr>
          <tr>
            <td>
              <label for="keyfields" id="keyfieldslabel"></label><br/>
              <select id="keyfields" size="5" multiple="multiple"><option></option></select>
            </td>
            <td>
              <input type="button" id="keyleft" value="&lt;&lt;" /><br/>
              <input type="button" id="keyright" value="&gt;&gt;" /><br/>
            </td>
            <td>
              <label for="keyavail" id="keyavaillabel"></label><br/>
              <select id="keyavail" size="5" multiple="multiple"><option></option></select>
            </td>
          </tr>
        </tbody>
      </table>
    </fieldset>
  </div>

  <div id="table">
    <table>
      <tbody>
        <tr>
          <td>
            <label id="tablenamelabel" for="tablename"></label>
          </td>
          <td>
            <input id="tablename" type="text" />
          </td>
        </tr>
        <tr>
          <td>
            <label id="tablecommentlabel" for="tablecomment"></label>
          </td>
          <td>
            <textarea rows="5" cols="40" id="tablecomment"></textarea>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

<%= content_for :after_js do %>
  <script type="text/javascript">
    var designer = new SQL.Designer();
    designer.languageResponse((new DOMParser()).parseFromString(
      '<%= j raw File.read(Rails.root.join("app/assets/javascripts/wwwsqldesigner/locale/en.xml")) %>',
      'text/xml'));
    designer.dbResponse((new DOMParser()).parseFromString(
      '<%= j raw File.read(Rails.root.join("app/assets/javascripts/wwwsqldesigner/db/postgresql/datatypes.xml")) %>',
      'text/xml'));

    designer.setSaveUrl('<%= db_schema_path(@db_schema, authenticity_token: form_authenticity_token) %>');
    designer.io.loadresponse((new DOMParser()).parseFromString(
      '<%= j raw @db_schema.content %>', 'text/xml'), 200);
  </script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/layouts/sqldesigner.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "wwwsqldesigner" %>
  </head>
  <body>
    <%= yield %>
    <%= javascript_include_tag "wwwsqldesigner/wwwsqldesigner_packed" %>
    <%= yield :after_js %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>
  <div class="navbar-title">
    <%= image_tag "db_logo.svg", height: "30" %>
    <h1>DBShare</h1>
  </div>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>